name: Check and Test

on:
  push:

jobs:
  Check-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with: 
        python-version: "3.10"
    - name: Run Linting and Type Checking
      run: make check
    - name: Run Unit Tests
      run: make test